<a href="https://colab.research.google.com/github/aadityane93/SortingLine-ml/blob/main/Feature_Selection_and_Model_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tsfresh
from google.colab import files
import numpy as np
import pandas as pd
from tsfresh import extract_features, select_features
from tsfresh.utilities.dataframe_functions import impute
from tsfresh.feature_selection.relevance import calculate_relevance_table
from sklearn.model_selection import train_test_split, KFold, cross_val_predict, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score
import xgboost as xgb

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.0/96.0 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.5/176.5 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 31.0 MB/s eta 0:00:00


In [ ]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
import os

# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
# folder_id = '1fX9iKRJcP8UwyI_xhI-TlJdxQj1NzvBz' # 20% files
# folder_id ='1WFFJcTKOLcoFFzzm29Ch33qotT2h5gX3' #50% files
folder_id ='1lcYHGesfAhSlpaJu3CwDWo65R6bnaqCo' #80% files

folder_list = drive.ListFile({'q': "'{}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false".format(folder_id)}).GetList()


for folder in folder_list:
    folder_title = folder['title']
    print(f"Processing folder: {folder_title}")
    file_list = drive.ListFile({'q': "'{}' in parents and trashed=false".format(folder['id'])}).GetList()

    for index, file in enumerate(file_list):
        file_title = file['title']
        print(f"Downloading {file_title}")
        file.GetContentFile(file_title)

Processing folder: 800hz extracted
Processing folder: 400hz extracted
Processing folder: 100hz extracted


In [ ]:
hz = 100
percent = 80

In [ ]:
def read_file(filename):
  return pd.read_csv(filename, sep=',')

extracted_train_feature = pd.DataFrame(read_file(f'extracted-{hz}hz-train-feature-{percent}percent.csv'))
extracted_test_feature = pd.DataFrame(read_file(f'extracted-{hz}hz-test-feature-{percent}percent.csv'))
extracted_train_target = pd.DataFrame(read_file(f'extracted-{hz}hz-train-target-{percent}percent.csv'))
extracted_test_target = pd.DataFrame(read_file(f'extracted-{hz}hz-test-target-{percent}percent.csv'))

In [ ]:
extracted_train_target = extracted_train_target.drop(columns=['Unnamed: 0'])
extracted_test_target = extracted_test_target.drop(columns=['Unnamed: 0'])
extracted_train_feature = extracted_train_feature.drop(columns=['Unnamed: 0'])
extracted_test_feature = extracted_test_feature.drop(columns=['Unnamed: 0'])

In [ ]:
extracted_train_feature.head()

I_In__variance_larger_than_standard_deviation  I_In__has_duplicate_max  \
0                                            0.0                      1.0   
1                                            0.0                      0.0   
2                                            0.0                      0.0   
3                                            0.0                      0.0   
4                                            0.0                      1.0   

   I_In__has_duplicate_min  I_In__has_duplicate  I_In__sum_values  \
0                      1.0                  1.0            250.81   
1                      0.0                  1.0            250.05   
2                      1.0                  1.0            231.03   
3                      1.0                  1.0            219.25   
4                      1.0                  1.0            239.70   

   I_In__abs_energy  I_In__mean_abs_change  I_In__mean_change  \
0          101.4769               0.038292           0.000415   
1          102.0841               0.042379           0.000389   
2           94.2721               0.041493           0.000520   
3           89.8207               0.042157           0.000481   
4           98.4812               0.040408           0.000408   

   I_In__mean_second_derivative_central  I_In__median  ...  \
0                              0.000000          0.37  ...   
1                              0.000047          0.37  ...   
2                             -0.000067          0.37  ...   
3                             -0.000054          0.37  ...   
4                             -0.000033          0.37  ...   

   Temp(°C)__fourier_entropy__bins_5  Temp(°C)__fourier_entropy__bins_10  \
0                           1.280506                            1.919827   
1                           1.123708                            1.765862   
2                           1.092491                            1.741591   
3                           1.346895                            2.015920   
4                           1.158979                            1.819628   

   Temp(°C)__fourier_entropy__bins_100  \
0                             3.842121   
1                             3.701585   
2                             3.702245   
3                             3.921954   
4                             3.760082   

   Temp(°C)__permutation_entropy__dimension_3__tau_1  \
0                                           1.386197   
1                                           1.398722   
2                                           1.364469   
3                                           1.462090   
4                                           1.356556   

   Temp(°C)__permutation_entropy__dimension_4__tau_1  \
0                                           2.285083   
1                                           2.307939   
2                                           2.287314   
3                                           2.406550   
4                                           2.270489   

   Temp(°C)__permutation_entropy__dimension_5__tau_1  \
0                                           3.157043   
1                                           3.216146   
2                                           3.155369   
3                                           3.360859   
4                                           3.194101   

   Temp(°C)__permutation_entropy__dimension_6__tau_1  \
0                                           3.966588   
1                                           4.018596   
2                                           3.939051   
3                                           4.188281   
4                                           4.025864   

   Temp(°C)__permutation_entropy__dimension_7__tau_1  \
0                                           4.670473   
1                                           4.716842   
2                                           4.591458   
3                                           4.904547   
4                      

In [ ]:
selected_features_train = select_features(extracted_train_feature, extracted_train_target['color'])

In [ ]:
selected_features_test = extracted_test_feature[selected_features_train.columns]

In [ ]:
selected_features_train

I_In__sum_values  I_In__abs_energy  \
0               250.81          101.4769   
1               250.05          102.0841   
2               231.03           94.2721   
3               219.25           89.8207   
4               239.70           98.4812   
...                ...               ...   
3195            352.18          141.8978   
3196            329.48          133.5894   
3197            330.26          132.7940   
3198            324.97          132.7549   
3199            337.20          136.5026   

      I_In__time_reversal_asymmetry_statistic__lag_3  \
0                                           0.000343   
1                                           0.000296   
2                                           0.000156   
3                                           0.000469   
4                                           0.000687   
...                                              ...   
3195                                       -0.000635   
3196                                       -0.000389   
3197                                        0.000345   
3198                                        0.000367   
3199                                       -0.000332   

      I_Out(A)__fft_coefficient__attr_"abs"__coeff_0  \
0                                             197.85   
1                                             198.61   
2                                             184.07   
3                                             174.96   
4                                             189.20   
...                                              ...   
3195                                          281.50   
3196                                          261.90   
3197                                          265.31   
3198                                          256.86   
3199                                          266.82   

      I_In__ratio_value_number_to_time_series_length  \
0                                           0.039939   
1                                           0.043478   
2                                           0.045226   
3                                           0.048043   
4                                           0.045677   
...                                              ...   
3195                                        0.026345   
3196                                        0.033136   
3197                                        0.030516   
3198                                        0.031250   
3199                                        0.032221   

      Temp(°C)__fft_coefficient__attr_"abs"__coeff_0  \
0                                           22754.88   
1                                           22512.10   
2                                           20863.58   
3                                           19669.41   
4                                           21460.76   
...                                              ...   
3195                                        31072.07   
3196                                        28817.15   
3197                                        29060.49   
3198                                        28373.59   
3199                                        29626.53   

      I_In__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"max"  \
0                                              0.026000                 
1                                              0.026978                 
2                                              0.035070                 
3                                              0.023497                 
4                                              0.027198                 
...                                                 ...                 
3195                                           0.017474                 
3196                                           0.025098                 
3197                                           0.014923                 
3198                                           0.028946

In [ ]:
selected_features_test

I_In__sum_values  I_In__abs_energy  \
0              244.63           99.5949   
1              219.19           89.9539   
2              242.14           98.3714   
3              244.42           99.4244   
4              230.04           93.4120   
..                ...               ...   
795            278.04           88.2192   
796            277.34           88.2342   
797            267.63           85.0573   
798            263.57           83.2995   
799            267.19           85.8083   

     I_In__time_reversal_asymmetry_statistic__lag_3  \
0                                          0.000238   
1                                          0.000573   
2                                          0.000372   
3                                          0.000245   
4                                          0.000845   
..                                              ...   
795                                       -0.000217   
796                                       -0.000186   
797                                       -0.000192   
798                                       -0.000226   
799                                       -0.000340   

     I_Out(A)__fft_coefficient__attr_"abs"__coeff_0  \
0                                            196.57   
1                                            173.89   
2                                            190.56   
3                                            193.35   
4                                            181.66   
..                                              ...   
795                                          282.74   
796                                          282.23   
797                                          271.06   
798                                          270.40   
799                                          269.13   

     I_In__ratio_value_number_to_time_series_length  \
0                                          0.038035   
1                                          0.044563   
2                                          0.040064   
3                                          0.039683   
4                                          0.042373   
..                                              ...   
795                                        0.026345   
796                                        0.025358   
797                                        0.022883   
798                                        0.025434   
799                                        0.026498   

     Temp(°C)__fft_coefficient__attr_"abs"__coeff_0  \
0                                          19627.52   
1                                          17439.16   
2                                          19384.97   
3                                          19577.13   
4                                          18324.06   
..                                              ...   
795                                        34539.93   
796                                        34393.41   
797                                        33144.87   
798                                        32812.70   
799                                        32937.84   

     I_In__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"max"  \
0                                             0.027527                 
1                                             0.033357                 
2                                             0.024011                 
3                                             0.022967                 
4                                             0.024476                 
..                                                 ...                 
795                                           0.016544                 
796                                           0.008842                 
797                                           0.013674                 
798                                           0.008452                 
799                                           0.0108

In [ ]:
extracted_test_target

color
0        0
1        0
2        0
3        0
4        0
..     ...
795      3
796      3
797      3
798      3
799      3

[800 rows x 1 columns]

In [ ]:
model = RandomForestClassifier()
model.fit(selected_features_train,extracted_train_target)
y_pred = model.predict(selected_features_test)
accuracy = accuracy_score(extracted_test_target, y_pred)
precision = precision_score(extracted_test_target, y_pred, average='weighted')
print(classification_report(extracted_test_target, y_pred))
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(confusion_matrix(extracted_test_target, y_pred))

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


              precision    recall  f1-score   support

           0       0.99      0.97      0.98       200
           1       0.44      0.62      0.52       200
           2       0.87      0.17      0.28       200
           3       0.70      1.00      0.82       200

    accuracy                           0.69       800
   macro avg       0.75      0.69      0.65       800
weighted avg       0.75      0.69      0.65       800

Accuracy: 0.6887
Precision: 0.7499
[[194   1   5   0]
 [  0 124   0  76]
 [  2 154  33  11]
 [  0   0   0 200]]


In [ ]:
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score

final_model = xgb.XGBClassifier(
    # objective="multi:softmax",
    # random_state=42,
    alpha=10,
    reg_lambda=1,
    # max_depth=10,
    min_child_weight=10,
    # subsample=0.8,
    colsample_bytree=0.8
)

final_model.fit(selected_features_train,extracted_train_target)
y_pred = final_model.predict(selected_features_test)
accuracy = accuracy_score(extracted_test_target, y_pred)
precision = precision_score(extracted_test_target, y_pred, average='weighted')
print(classification_report(extracted_test_target, y_pred))
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(confusion_matrix(extracted_test_target, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       200
           1       0.99      0.94      0.96       200
           2       1.00      0.97      0.99       200
           3       0.92      0.99      0.95       200

    accuracy                           0.97       800
   macro avg       0.98      0.97      0.98       800
weighted avg       0.98      0.97      0.98       800

Accuracy: 0.9750
Precision: 0.9766
[[198   0   0   2]
 [  0 188   0  12]
 [  0   1 195   4]
 [  0   1   0 199]]
