<a href="https://colab.research.google.com/github/aadityane93/SortingLine-ml/blob/main/Feature_Selection_and_Model_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
!pip install tsfresh
from google.colab import files
import numpy as np
import pandas as pd
from tsfresh import extract_features, select_features
from tsfresh.utilities.dataframe_functions import impute
from tsfresh.feature_selection.relevance import calculate_relevance_table
from sklearn.model_selection import train_test_split, KFold, cross_val_predict, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score
import xgboost as xgb

In [3]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
import os

# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
folder_id = '15myxitNBue9FKPBvNm-j_FS_fiElz3C8' # files

folder_list = drive.ListFile({'q': "'{}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false".format(folder_id)}).GetList()


for folder in folder_list:
    folder_title = folder['title']
    print(f"Processing folder: {folder_title}")
    file_list = drive.ListFile({'q': "'{}' in parents and trashed=false".format(folder['id'])}).GetList()

    for index, file in enumerate(file_list):
        file_title = file['title']
        print(f"Downloading {file_title}")
        file.GetContentFile(file_title)

Processing folder: 1000 files
Processing folder: 100 files
Processing folder: 10 files


In [6]:
def read_file(filename):
  return pd.read_csv(filename, sep=',')

extracted_train_feature = pd.DataFrame(read_file('extracted-100hz-train-feature-50percent-100files.csv'))
extracted_test_feature = pd.DataFrame(read_file('extracted-100hz-test-feature-50percent-100files.csv'))
extracted_train_target = pd.DataFrame(read_file('extracted-100hz-train-target-50percent-100files.csv'))
extracted_test_target = pd.DataFrame(read_file('extracted-100hz-test-target-50percent-100files.csv'))

In [9]:
extracted_train_target = extracted_train_target.drop(columns=['Unnamed: 0'])
extracted_test_target = extracted_test_target.drop(columns=['Unnamed: 0'])
extracted_train_feature = extracted_train_feature.drop(columns=['Unnamed: 0'])
extracted_test_feature = extracted_test_feature.drop(columns=['Unnamed: 0'])

In [27]:
extracted_train_feature.head()

I_In__variance_larger_than_standard_deviation  I_In__has_duplicate_max  \
0                                            0.0                      0.0   
1                                            0.0                      0.0   
2                                            0.0                      0.0   
3                                            0.0                      0.0   
4                                            0.0                      0.0   

   I_In__has_duplicate_min  I_In__has_duplicate  I_In__sum_values  \
0                      1.0                  1.0            189.99   
1                      1.0                  1.0            185.58   
2                      1.0                  1.0            184.09   
3                      0.0                  1.0            187.40   
4                      1.0                  1.0            183.78   

   I_In__abs_energy  I_In__mean_abs_change  I_In__mean_change  \
0           60.2121               0.042299           0.000305   
1           59.6738               0.042040           0.000216   
2           59.0125               0.043344           0.000250   
3           60.1416               0.042311           0.000246   
4           59.4834               0.041930           0.000285   

   I_In__mean_second_derivative_central  I_In__median  ...  \
0                         -8.051530e-06          0.29  ...   
1                          0.000000e+00          0.29  ...   
2                         -4.625929e-20          0.30  ...   
3                         -1.642036e-05          0.29  ...   
4                          1.680672e-05          0.29  ...   

   Temp(°C)__fourier_entropy__bins_5  Temp(°C)__fourier_entropy__bins_10  \
0                           1.204209                            1.795131   
1                           1.436031                            2.089244   
2                           1.139872                            1.786103   
3                           1.219551                            1.839760   
4                           1.211701                            1.898553   

   Temp(°C)__fourier_entropy__bins_100  \
0                             3.805391   
1                             4.045644   
2                             3.792321   
3                             3.856714   
4                             3.854095   

   Temp(°C)__permutation_entropy__dimension_3__tau_1  \
0                                           1.318114   
1                                           1.410305   
2                                           1.462869   
3                                           1.485377   
4                                           1.467557   

   Temp(°C)__permutation_entropy__dimension_4__tau_1  \
0                                           2.152424   
1                                           2.314589   
2                                           2.450789   
3                                           2.524549   
4                                           2.479623   

   Temp(°C)__permutation_entropy__dimension_5__tau_1  \
0                                           2.987462   
1                                           3.235639   
2                                           3.414714   
3                                           3.559655   
4                                           3.458075   

   Temp(°C)__permutation_entropy__dimension_6__tau_1  \
0                                           3.746941   
1                                           4.075079   
2                                           4.310813   
3                                           4.512030   
4                                           4.381721   

   Temp(°C)__permutation_entropy__dimension_7__tau_1  \
0                                           4.391745   
1                                           4.799483   
2                                           5.059538   
3                                           5.219138   
4                      

In [22]:
selected_features_train = select_features(extracted_train_feature, extracted_train_target['color'])

In [24]:
selected_features_test = extracted_test_feature[selected_features_train.columns]

In [25]:
selected_features_train.head()

I_Out(A)__sum_of_reoccurring_data_points  \
0                                    189.20   
1                                    183.39   
2                                    182.81   
3                                    183.34   
4                                    182.58   

   I_In__fft_aggregated__aggtype_"variance"  \
0                              10023.276497   
1                               8893.805173   
2                               9239.818040   
3                               9143.044817   
4                               8209.689272   

   I_Out(A)__fft_coefficient__attr_"angle"__coeff_1  \
0                                         12.281726   
1                                         13.918459   
2                                         13.999959   
3                                         14.953357   
4                                         11.591896   

   I_In__sum_of_reoccurring_data_points  \
0                                186.58   
1                                182.01   
2                                181.48   
3                                183.44   
4                                178.62   

   Temp(°C)__fft_coefficient__attr_"abs"__coeff_0  \
0                                        23397.99   
1                                        22658.52   
2                                        22567.51   
3                                        22888.18   
4                                        22371.61   

   Temp(°C)__fft_coefficient__attr_"real"__coeff_0  Temp(°C)__abs_energy  \
0                                         23397.99           878768.6987   
1                                         22658.52           850026.7576   
2                                         22567.51           846013.1913   
3                                         22888.18           857410.4134   
4                                         22371.61           838352.7793   

   Temp(°C)__sum_values  Temp(°C)__sum_of_reoccurring_data_points  \
0              23397.99                                  23397.99   
1              22658.52                                  22658.52   
2              22567.51                                  22567.51   
3              22888.18                                  22888.18   
4              22371.61                                  22371.61   

   I_Out(A)__range_count__max_1__min_-1  ...  \
0                                 622.0  ...   
1                                 602.0  ...   
2                                 601.0  ...   
3                                 610.0  ...   
4                                 596.0  ...   

   I_Out(A)__fft_coefficient__attr_"abs"__coeff_52  \
0                                         1.936640   
1                                         1.709872   
2                                         1.248486   
3                                         1.589452   
4                                         1.036741   

   I_In__fft_coefficient__attr_"abs"__coeff_18  \
0                                     2.818966   
1                                     2.444789   
2                                     2.373812   
3                                     2.286361   
4                                     2.623803   

   I_In__fft_coefficient__attr_"abs"__coeff_49  \
0                                     0.864501   
1                                     2.194649   
2                                     0.837620   
3                                     1.707862   
4                                     2.911375   

   Temp(°C)__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.4  \
0                                           0.009772                      
1                                           0.115036                      
2                                           0.122736                      
3                                           0.120370                      
4                                           0.122650             

In [26]:
selected_features_test.head()

I_Out(A)__sum_of_reoccurring_data_points  \
0                                    194.29   
1                                    185.65   
2                                    183.82   
3                                    190.41   
4                                    193.53   

   I_In__fft_aggregated__aggtype_"variance"  \
0                              10332.511806   
1                               7804.108885   
2                               8041.320629   
3                              10079.223927   
4                               9745.087070   

   I_Out(A)__fft_coefficient__attr_"angle"__coeff_1  \
0                                          9.374856   
1                                         -2.541205   
2                                         11.374796   
3                                         14.866742   
4                                         12.739791   

   I_In__sum_of_reoccurring_data_points  \
0                                192.58   
1                                181.63   
2                                182.05   
3                                187.37   
4                                191.33   

   Temp(°C)__fft_coefficient__attr_"abs"__coeff_0  \
0                                        24193.48   
1                                        22690.78   
2                                        22536.02   
3                                        23354.38   
4                                        23916.08   

   Temp(°C)__fft_coefficient__attr_"real"__coeff_0  Temp(°C)__abs_energy  \
0                                         24193.48           906088.1374   
1                                         22690.78           849634.4864   
2                                         22536.02           840855.5326   
3                                         23354.38           871297.3094   
4                                         23916.08           892330.7854   

   Temp(°C)__sum_values  Temp(°C)__sum_of_reoccurring_data_points  \
0              24193.48                                  24193.48   
1              22690.78                                  22690.78   
2              22536.02                                  22536.02   
3              23354.38                                  23354.38   
4              23916.08                                  23916.08   

   I_Out(A)__range_count__max_1__min_-1  ...  \
0                                 644.0  ...   
1                                 604.0  ...   
2                                 602.0  ...   
3                                 625.0  ...   
4                                 639.0  ...   

   I_Out(A)__fft_coefficient__attr_"abs"__coeff_52  \
0                                         2.012123   
1                                        84.492819   
2                                         1.561495   
3                                         2.542209   
4                                         2.824340   

   I_In__fft_coefficient__attr_"abs"__coeff_18  \
0                                     1.215364   
1                                    89.877914   
2                                     2.385978   
3                                     1.989706   
4                                     1.727575   

   I_In__fft_coefficient__attr_"abs"__coeff_49  \
0                                     0.932181   
1                                    89.090469   
2                                     1.493075   
3                                     1.243267   
4                                     1.689163   

   Temp(°C)__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.4  \
0                                           0.107080                      
1                                           0.123134                      
2                                           0.000000                      
3                                           0.000000                      
4                                           0.000000             

In [20]:
extracted_train_target

color
0        0
1        0
2        0
3        0
4        0
..     ...
195      3
196      3
197      3
198      3
199      3

[200 rows x 1 columns]

In [30]:
model = RandomForestClassifier()
model.fit(selected_features_train,extracted_train_target)
y_pred = model.predict(selected_features_test)
accuracy = accuracy_score(extracted_train_target, y_pred)
print(f"Accuracy: {accuracy}")
print(classification_report(extracted_train_target, y_pred))
print(confusion_matrix(extracted_train_target, y_pred))

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Accuracy: 0.855
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        50
           1       0.93      0.52      0.67        50
           2       0.65      1.00      0.79        50
           3       1.00      0.96      0.98        50

    accuracy                           0.85       200
   macro avg       0.89      0.85      0.85       200
weighted avg       0.89      0.85      0.85       200

[[47  0  3  0]
 [ 0 26 24  0]
 [ 0  0 50  0]
 [ 0  2  0 48]]
