<a href="https://colab.research.google.com/github/aadityane93/SortingLine-ml/blob/main/Feature_Selection_and_Model_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
!pip install tsfresh
from google.colab import files
import numpy as np
import pandas as pd
from tsfresh import extract_features, select_features
from tsfresh.utilities.dataframe_functions import impute
from tsfresh.feature_selection.relevance import calculate_relevance_table
from sklearn.model_selection import train_test_split, KFold, cross_val_predict, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score
import xgboost as xgb

In [3]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
import os

# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
folder_id = '15myxitNBue9FKPBvNm-j_FS_fiElz3C8' # files

folder_list = drive.ListFile({'q': "'{}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false".format(folder_id)}).GetList()


for folder in folder_list:
    folder_title = folder['title']
    print(f"Processing folder: {folder_title}")
    file_list = drive.ListFile({'q': "'{}' in parents and trashed=false".format(folder['id'])}).GetList()

    for index, file in enumerate(file_list):
        file_title = file['title']
        print(f"Downloading {file_title}")
        file.GetContentFile(file_title)

Processing folder: 1000 files
Processing folder: 100 files
Processing folder: 10 files


In [42]:
def read_file(filename):
  return pd.read_csv(filename, sep=',')

extracted_train_feature = pd.DataFrame(read_file('extracted-100hz-train-feature-20percent-1000files.csv'))
extracted_test_feature = pd.DataFrame(read_file('extracted-100hz-test-feature-20percent-1000files.csv'))
extracted_train_target = pd.DataFrame(read_file('extracted-100hz-train-target-20percent-1000files.csv'))
extracted_test_target = pd.DataFrame(read_file('extracted-100hz-test-target-20percent-1000files.csv'))

In [43]:
extracted_train_target = extracted_train_target.drop(columns=['Unnamed: 0'])
extracted_test_target = extracted_test_target.drop(columns=['Unnamed: 0'])
extracted_train_feature = extracted_train_feature.drop(columns=['Unnamed: 0'])
extracted_test_feature = extracted_test_feature.drop(columns=['Unnamed: 0'])

In [44]:
extracted_train_feature.head()

I_In__variance_larger_than_standard_deviation  I_In__has_duplicate_max  \
0                                            0.0                      1.0   
1                                            0.0                      0.0   
2                                            0.0                      0.0   
3                                            0.0                      0.0   
4                                            0.0                      1.0   

   I_In__has_duplicate_min  I_In__has_duplicate  I_In__sum_values  \
0                      1.0                  1.0            250.81   
1                      0.0                  1.0            250.05   
2                      1.0                  1.0            231.03   
3                      1.0                  1.0            219.25   
4                      1.0                  1.0            239.70   

   I_In__abs_energy  I_In__mean_abs_change  I_In__mean_change  \
0          101.4769               0.038292           0.000415   
1          102.0841               0.042379           0.000389   
2           94.2721               0.041493           0.000520   
3           89.8207               0.042157           0.000481   
4           98.4812               0.040408           0.000408   

   I_In__mean_second_derivative_central  I_In__median  ...  \
0                              0.000000          0.37  ...   
1                              0.000047          0.37  ...   
2                             -0.000067          0.37  ...   
3                             -0.000054          0.37  ...   
4                             -0.000033          0.37  ...   

   Temp(°C)__fourier_entropy__bins_5  Temp(°C)__fourier_entropy__bins_10  \
0                           1.280506                            1.919827   
1                           1.123708                            1.765862   
2                           1.092491                            1.741591   
3                           1.346895                            2.015920   
4                           1.158979                            1.819628   

   Temp(°C)__fourier_entropy__bins_100  \
0                             3.842121   
1                             3.701585   
2                             3.702245   
3                             3.921954   
4                             3.760082   

   Temp(°C)__permutation_entropy__dimension_3__tau_1  \
0                                           1.386197   
1                                           1.398722   
2                                           1.364469   
3                                           1.462090   
4                                           1.356556   

   Temp(°C)__permutation_entropy__dimension_4__tau_1  \
0                                           2.285083   
1                                           2.307939   
2                                           2.287314   
3                                           2.406550   
4                                           2.270489   

   Temp(°C)__permutation_entropy__dimension_5__tau_1  \
0                                           3.157043   
1                                           3.216146   
2                                           3.155369   
3                                           3.360859   
4                                           3.194101   

   Temp(°C)__permutation_entropy__dimension_6__tau_1  \
0                                           3.966588   
1                                           4.018596   
2                                           3.939051   
3                                           4.188281   
4                                           4.025864   

   Temp(°C)__permutation_entropy__dimension_7__tau_1  \
0                                           4.670473   
1                                           4.716842   
2                                           4.591458   
3                                           4.904547   
4                      

In [45]:
selected_features_train = select_features(extracted_train_feature, extracted_train_target['color'])

In [46]:
selected_features_test = extracted_test_feature[selected_features_train.columns]

In [52]:
selected_features_train

Temp(°C)__quantile__q_0.7  Temp(°C)__quantile__q_0.8  \
0                        35.13                      35.13   
1                        35.13                      35.13   
2                        35.13                      35.13   
3                        35.13                      35.13   
4                        35.13                      35.13   
..                         ...                        ...   
795                      32.87                      32.87   
796                      32.87                      32.87   
797                      32.87                      32.87   
798                      32.87                      32.87   
799                      32.87                      32.87   

     Temp(°C)__quantile__q_0.6  Temp(°C)__median  Temp(°C)__quantile__q_0.9  \
0                        34.87             34.87                      35.13   
1                        34.87             34.87                      35.13   
2                        34.87             34.87                      35.13   
3                        35.13             35.13                      35.13   
4                        35.13             35.13                      35.13   
..                         ...               ...                        ...   
795                      32.87             32.87                      32.87   
796                      32.87             32.87                      32.87   
797                      32.87             32.87                      32.87   
798                      32.87             32.87                      32.87   
799                      32.87             32.87                      32.87   

     Temp(°C)__quantile__q_0.4  Temp(°C)__quantile__q_0.1  Temp(°C)__minimum  \
0                        34.87                      34.87              34.62   
1                        34.87                      34.87              34.62   
2                        34.87                      34.87              34.62   
3                        34.87                      34.87              34.62   
4                        34.87                      34.87              34.62   
..                         ...                        ...                ...   
795                      32.87                      32.87              32.62   
796                      32.87                      32.87              32.62   
797                      32.87                      32.62              32.62   
798                      32.87                      32.62              32.62   
799                      32.87                      32.62              32.62   

     Temp(°C)__quantile__q_0.3  \
0                        34.87   
1                        34.87   
2                        34.87   
3                        34.87   
4                        34.87   
..                         ...   
795                      32.87   
796                      32.87   
797                      32.87   
798                      32.87   
799                      32.62   

     Temp(°C)__mean_n_absolute_max__number_of_maxima_7  ...  \
0                                                35.13  ...   
1                                                35.13  ...   
2                                                35.13  ...   
3                                                35.13  ...   
4                                                35.13  ...   
..                                                 ...  ...   
795                                              33.12  ...   
796                                              33.12  ...   
797                                              33.12  ...   
798                                              33.12  ...   
799                                              32.87  ...   

     V_Out(V)__sample_entropy  Temp(°C)__partial_autocorrelation__lag_3  \
0                    0.722427                                 -0.021780   
1                    0.736839                 

In [51]:
selected_features_test

Temp(°C)__quantile__q_0.7  Temp(°C)__quantile__q_0.8  \
0                         35.38                      35.38   
1                         35.38                      35.38   
2                         35.38                      35.38   
3                         35.38                      35.38   
4                         35.38                      35.38   
...                         ...                        ...   
3195                      37.88                      38.13   
3196                      37.88                      38.13   
3197                      37.88                      38.13   
3198                      37.88                      38.13   
3199                      38.13                      38.13   

      Temp(°C)__quantile__q_0.6  Temp(°C)__median  Temp(°C)__quantile__q_0.9  \
0                         35.38             35.38                      35.38   
1                         35.38             35.38                      35.63   
2                         35.38             35.38                      35.63   
3                         35.38             35.38                      35.38   
4                         35.38             35.38                      35.63   
...                         ...               ...                        ...   
3195                      37.88             37.88                      38.13   
3196                      37.88             37.88                      38.13   
3197                      37.88             37.88                      38.13   
3198                      37.88             37.88                      38.13   
3199                      37.88             37.88                      38.13   

      Temp(°C)__quantile__q_0.4  Temp(°C)__quantile__q_0.1  Temp(°C)__minimum  \
0                         35.38                      35.38              35.13   
1                         35.38                      35.38              35.13   
2                         35.38                      35.38              35.13   
3                         35.38                      35.38              35.13   
4                         35.38                      35.38              35.13   
...                         ...                        ...                ...   
3195                      37.88                      37.88              37.63   
3196                      37.88                      37.88              37.63   
3197                      37.88                      37.88              37.63   
3198                      37.88                      37.88              37.63   
3199                      37.88                      37.88              37.63   

      Temp(°C)__quantile__q_0.3  \
0                         35.38   
1                         35.38   
2                         35.38   
3                         35.38   
4                         35.38   
...                         ...   
3195                      37.88   
3196                      37.88   
3197                      37.88   
3198                      37.88   
3199                      37.88   

      Temp(°C)__mean_n_absolute_max__number_of_maxima_7  ...  \
0                                                 35.63  ...   
1                                                 35.63  ...   
2                                                 35.63  ...   
3                                                 35.63  ...   
4                                                 35.63  ...   
...                                                 ...  ...   
3195                                              38.13  ...   
3196                                              38.13  ...   
3197                                              38.13  ...   
3198                                              38.13  ...   
3199                                              38.13  ...   

      V_Out(V)__sample_entropy  Temp(°C)__partial_autocorrelation__lag_3  \
0                     0.749920                               

In [53]:
extracted_test_target

color
0         0
1         0
2         0
3         0
4         0
...     ...
3195      3
3196      3
3197      3
3198      3
3199      3

[3200 rows x 1 columns]

In [61]:
model = RandomForestClassifier()
model.fit(selected_features_train,extracted_train_target)
y_pred = model.predict(selected_features_test)
accuracy = accuracy_score(extracted_test_target, y_pred)
precision = precision_score(extracted_test_target, y_pred, average='weighted')
print(classification_report(extracted_test_target, y_pred))
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(confusion_matrix(extracted_test_target, y_pred))

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


              precision    recall  f1-score   support

           0       0.99      0.92      0.96       800
           1       0.99      0.33      0.50       800
           2       0.47      0.87      0.61       800
           3       0.73      0.66      0.70       800

    accuracy                           0.70      3200
   macro avg       0.80      0.70      0.69      3200
weighted avg       0.80      0.70      0.69      3200

Accuracy: 0.6969
Precision: 0.7970
[[739   0  58   3]
 [  0 267 443  90]
 [  4   3 694  99]
 [  0   1 269 530]]


In [64]:
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score

final_model = xgb.XGBClassifier(
    # objective="multi:softmax",
    # random_state=42,
    alpha=10,
    reg_lambda=1,
    # max_depth=10,
    min_child_weight=10,
    # subsample=0.8,
    colsample_bytree=0.8
)

final_model.fit(selected_features_train,extracted_train_target)
y_pred = final_model.predict(selected_features_test)
accuracy = accuracy_score(extracted_test_target, y_pred)
precision = precision_score(extracted_test_target, y_pred, average='weighted')
print(classification_report(extracted_test_target, y_pred))
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(confusion_matrix(extracted_test_target, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.77      0.86       800
           1       0.61      0.69      0.64       800
           2       0.73      0.85      0.78       800
           3       0.72      0.66      0.69       800

    accuracy                           0.74      3200
   macro avg       0.76      0.74      0.74      3200
weighted avg       0.76      0.74      0.74      3200

Accuracy: 0.7406
Precision: 0.7585
[[612  73  93  22]
 [  0 550 160  90]
 [ 11  14 678  97]
 [  0 269   1 530]]
