<a href="https://colab.research.google.com/github/aadityane93/SortingLine-ml/blob/main/wavelets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tsfresh
import pywt

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.0/96.0 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.5/176.5 kB 10.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 27.6 MB/s eta 0:00:00


In [2]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
import os

# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
folder_id = '1ps_Bh93KQRJ4WbnilORmKd1BaWUXtmt1' # files

folder_list = drive.ListFile({'q': "'{}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false".format(folder_id)}).GetList()


for folder in folder_list:
    folder_title = folder['title']
    print(f"Processing folder: {folder_title}")
    file_list = drive.ListFile({'q': "'{}' in parents and trashed=false".format(folder['id'])}).GetList()

    for index, file in enumerate(file_list):
        file_title = file['title']
        print(f"Downloading {file_title}")
        file.GetContentFile(file_title)

Processing folder: 400hz
Processing folder: 100hz
Processing folder: 800hz


In [3]:
import pandas as pd

In [4]:
train_target = pd.read_csv('100hz-train-target-20percent-1000files.csv')
train_target.drop(columns=['Unnamed: 0'], inplace = True)
test_target = pd.read_csv('100hz-test-target-20percent-1000files.csv')
test_target.drop(columns=['Unnamed: 0'], inplace = True)
train_feature = pd.read_csv('100hz-train-feature-20percent-1000files.csv')
train_feature.drop(columns=['Unnamed: 0', 'Datum', 'Energie_In(Wh)','Energie_Out(Wh)', 'P_In(W)', 'P_Out(W)', 'color'], inplace = True)
test_feature = pd.read_csv('100hz-test-feature-20percent-1000files.csv')
test_feature.drop(columns=['Unnamed: 0', 'Datum', 'Energie_In(Wh)','Energie_Out(Wh)', 'P_In(W)', 'P_Out(W)', 'color' ], inplace = True)

In [5]:
train_feature

Uhrzeit  I_In  V_In  I_Out(A)  V_Out(V)  Temp(°C)  fileno
0       2024-08-14 19:17:58.406890:406  0.37  8.66      0.23      9.00     35.13       0
1       2024-08-14 19:17:58.414666:414  0.39  8.66      0.31      9.00     34.62       0
2       2024-08-14 19:17:58.422872:422  0.48  8.66      0.31      9.03     35.13       0
3       2024-08-14 19:17:58.435049:435  0.43  8.70      0.27      9.00     34.87       0
4       2024-08-14 19:17:58.443382:443  0.46  8.70      0.27      9.03     34.87       0
...                                ...   ...   ...       ...       ...       ...     ...
609718  2024-08-26 18:40:24.232560:232  0.37  8.75      0.31      9.03     32.87    3199
609719  2024-08-26 18:40:24.240992:240  0.33  8.70      0.31      9.03     32.87    3199
609720  2024-08-26 18:40:24.252801:252  0.31  8.75      0.23      9.03     32.62    3199
609721  2024-08-26 18:40:24.261297:261  0.37  8.75      0.31      9.00     32.62    3199
609722  2024-08-26 18:40:24.269744:269  0.33  8.79      0.31      9.00     32.62    3199

[609723 rows x 7 columns]

In [6]:
wavelet_type = 'db4'
decomp_level = 3

In [7]:
x_train_sorted = train_feature.sort_values(by=['fileno', 'Uhrzeit'])

# Group by fileno (each group is a time series)
grouped = x_train_sorted.groupby('fileno')

In [8]:
import numpy as np

In [9]:

# def tranform_ (column_):
#   wavelet_features = []
#   for fileno, group in grouped:
#       signal = group[f'{column_}'].values  # Example: Use power input

#       # Perform wavelet decomposition
#       coeffs = pywt.wavedec(signal, wavelet_type, level=decomp_level)

#       # Extract features from coefficients
#       features = {}
#       for i, coeff in enumerate(coeffs):
#           if len(coeff) == 0:
#               continue
#           # features: energy, entropy, variance
#           features[f'{column_}wavelet_energy_level_{i}'] = np.sum(coeff**2)
#           features[f'{column_}wavelet_entropy_level_{i}'] = -np.sum(coeff**2 * np.log(coeff**2 + 1e-10))
#           features[f'{column_}wavelet_var_level_{i}'] = np.var(coeff)

#       # Add fileno to map features back
#       # features['fileno'] = fileno
#   wavelet_features.append(features)
#   return wavelet_features

# i_in = tranform_("I_In")
# i_out = tranform_("I_Out(A)")
# v_in = tranform_("V_In")
# v_out = tranform_("V_Out(V)")

# # Convert to DataFrame
# # pywt.wavet features['fileno'] = fileno

# # wavelet_df = pd.DataFrame(wavelet_features).set_index('fileno')

In [10]:
wavelet_df_I_In = {}
wavelet_df_I_Out = {}
wavelet_df_V_In = {}
wavelet_df_V_Out = {}
wavelet_df_Temp = {}

wavelet_features_I_In = []
wavelet_features_I_Out =[]
wavelet_features_V_In =[]
wavelet_features_V_Out =[]
wavelet_features_Temp =[]


for fileno, group in grouped:
    signal_I_In = group['I_In'].values
    signal_V_In = group['V_In'].values
    signal_I_Out = group['I_Out(A)'].values
    signal_V_Out = group['V_Out(V)'].values
    signal_Temp = group['Temp(°C)'].values

    # wavelet decomposition
    coeffs_I_In = pywt.wavedec(signal_I_In, wavelet_type, level=decomp_level)
    coeffs_V_In = pywt.wavedec(signal_V_In, wavelet_type, level=decomp_level)
    coeffs_I_Out = pywt.wavedec(signal_I_Out, wavelet_type, level=decomp_level)
    coeffs_V_Out = pywt.wavedec(signal_V_Out, wavelet_type, level=decomp_level)
    coeffs_Temp = pywt.wavedec(signal_Temp, wavelet_type, level=decomp_level)

# for I_In

    # Extract features from coefficients
    features_I_In = {}
    for i, coeff in enumerate(coeffs_I_In):
        if len(coeff) == 0:
            continue
        # features: energy, entropy, variance
        features_I_In[f'I_In_wavelet_energy_level_{i}'] = np.sum(coeff**2)
        features_I_In[f'I_In_wavelet_entropy_level_{i}'] = -np.sum(coeff**2 * np.log(coeff**2 + 1e-10))
        features_I_In[f'I_In_wavelet_var_level_{i}'] = np.var(coeff)

    # Add fileno to map features back
    features_I_In['fileno'] = fileno
    wavelet_features_I_In.append(features_I_In)


#for I_Out
    features_I_Out = {}
    for i, coeff in enumerate(coeffs_I_Out):
        if len(coeff) == 0:
            continue
        # features: energy, entropy,
        features_I_Out[f'I_Out_wavelet_energy_level_{i}'] = np.sum(coeff**2)
        features_I_Out[f'I_Out_wavelet_entropy_level_{i}'] = -np.sum(coeff**2 * np.log(coeff**2 + 1e-10))
        features_I_Out[f'I_Out_wavelet_var_level_{i}'] = np.var(coeff)

    wavelet_features_I_Out.append(features_I_Out)



#for V_In
    features_V_In = {}
    for i, coeff in enumerate(coeffs_V_In):
        if len(coeff) == 0:
            continue
        # features: energy, entropy,
        features_V_In[f'V_In_wavelet_energy_level_{i}'] = np.sum(coeff**2)
        features_V_In[f'V_In_wavelet_entropy_level_{i}'] = -np.sum(coeff**2 * np.log(coeff**2 + 1e-10))
        features_V_In[f'V_In_wavelet_var_level_{i}'] = np.var(coeff)

    wavelet_features_V_In.append(features_V_In)


#for V_Out
    features_V_Out = {}
    for i, coeff in enumerate(coeffs_V_Out):
        if len(coeff) == 0:
            continue
        # features: energy, entropy,
        features_V_Out[f'V_Out_wavelet_energy_level_{i}'] = np.sum(coeff**2)
        features_V_Out[f'V_Out_wavelet_entropy_level_{i}'] = -np.sum(coeff**2 * np.log(coeff**2 + 1e-10))
        features_V_Out[f'V_Out_wavelet_var_level_{i}'] = np.var(coeff)

    wavelet_features_V_Out.append(features_V_Out)

#for Temp
    features_Temp = {}
    for i, coeff in enumerate(coeffs_Temp):
        if len(coeff) == 0:
            continue
        # features: energy, entropy,
        features_Temp[f'Temp_wavelet_energy_level_{i}'] = np.sum(coeff**2)
        features_Temp[f'Temp_wavelet_entropy_level_{i}'] = -np.sum(coeff**2 * np.log(coeff**2 + 1e-10))
        features_Temp[f'Temp_wavelet_var_level_{i}'] = np.var(coeff)

    wavelet_features_Temp.append(features_Temp)

# Convert to DataFrame
wavelet_df_I_In = pd.DataFrame(wavelet_features_I_In)
wavelet_df_I_Out = pd.DataFrame(wavelet_features_I_Out)
wavelet_df_V_In = pd.DataFrame(wavelet_features_V_In)
wavelet_df_V_Out = pd.DataFrame(wavelet_features_V_Out)
wavelet_df_Temp = pd.DataFrame(wavelet_features_Temp)


wavelet_df_train = pd.concat([wavelet_df_I_In, wavelet_df_I_Out, wavelet_df_V_In, wavelet_df_V_Out, wavelet_df_Temp], axis=1)
wavelet_df_train = wavelet_df_train.set_index('fileno')


In [11]:
wavelet_df_train.isna().sum()

I_In_wavelet_energy_level_0      0
I_In_wavelet_entropy_level_0     0
I_In_wavelet_var_level_0         0
I_In_wavelet_energy_level_1      0
I_In_wavelet_entropy_level_1     0
I_In_wavelet_var_level_1         0
I_In_wavelet_energy_level_2      0
I_In_wavelet_entropy_level_2     0
I_In_wavelet_var_level_2         0
I_In_wavelet_energy_level_3      0
I_In_wavelet_entropy_level_3     0
I_In_wavelet_var_level_3         0
I_Out_wavelet_energy_level_0     0
I_Out_wavelet_entropy_level_0    0
I_Out_wavelet_var_level_0        0
I_Out_wavelet_energy_level_1     0
I_Out_wavelet_entropy_level_1    0
I_Out_wavelet_var_level_1        0
I_Out_wavelet_energy_level_2     0
I_Out_wavelet_entropy_level_2    0
I_Out_wavelet_var_level_2        0
I_Out_wavelet_energy_level_3     0
I_Out_wavelet_entropy_level_3    0
I_Out_wavelet_var_level_3        0
V_In_wavelet_energy_level_0      0
V_In_wavelet_entropy_level_0     0
V_In_wavelet_var_level_0         0
V_In_wavelet_energy_level_1      0
V_In_wavelet_entropy_level_1     0
V_In_wavelet_var_level_1         0
V_In_wavelet_energy_level_2      0
V_In_wavelet_entropy_level_2     0
V_In_wavelet_var_level_2         0
V_In_wavelet_energy_level_3      0
V_In_wavelet_entropy_level_3     0
V_In_wavelet_var_level_3         0
V_Out_wavelet_energy_level_0     0
V_Out_wavelet_entropy_level_0    0
V_Out_wavelet_var_level_0        0
V_Out_wavelet_energy_level_1     0
V_Out_wavelet_entropy_level_1    0
V_Out_wavelet_var_level_1        0
V_Out_wavelet_energy_level_2     0
V_Out_wavelet_entropy_level_2    0
V_Out_wavelet_var_level_2        0
V_Out_wavelet_energy_level_3     0
V_Out_wavelet_entropy_level_3    0
V_Out_wavelet_var_level_3        0
Temp_wavelet_energy_level_0      0
Temp_wavelet_entropy_level_0     0
Temp_wavelet_var_level_0         0
Temp_wavelet_energy_level_1      0
Temp_wavelet_entropy_level_1     0
Temp_wavelet_var_level_1         0
Temp_wavelet_energy_level_2      0
Temp_wavelet_entropy_level_2     0
Temp_wavelet_var_level_2         0
Temp_wavelet_energy_level_3      0
Temp_wavelet_entropy_level_3     0
Temp_wavelet_var_level_3         0
dtype: int64

In [12]:
x_test_sorted = test_feature.sort_values(by=['fileno', 'Uhrzeit'])

# Group by fileno (each group is a time series)
grouped = x_test_sorted.groupby('fileno')

In [13]:
wavelet_df_I_In = {}
wavelet_df_I_Out = {}
wavelet_df_V_In = {}
wavelet_df_V_Out = {}
wavelet_df_Temp = {}

wavelet_features_I_In = []
wavelet_features_I_Out =[]
wavelet_features_V_In =[]
wavelet_features_V_Out =[]
wavelet_features_Temp =[]


for fileno, group in grouped:
    signal_I_In = group['I_In'].values
    signal_V_In = group['V_In'].values
    signal_I_Out = group['I_Out(A)'].values
    signal_V_Out = group['V_Out(V)'].values
    signal_Temp = group['Temp(°C)'].values

    # wavelet decomposition
    coeffs_I_In = pywt.wavedec(signal_I_In, wavelet_type, level=decomp_level)
    coeffs_V_In = pywt.wavedec(signal_V_In, wavelet_type, level=decomp_level)
    coeffs_I_Out = pywt.wavedec(signal_I_Out, wavelet_type, level=decomp_level)
    coeffs_V_Out = pywt.wavedec(signal_V_Out, wavelet_type, level=decomp_level)
    coeffs_Temp = pywt.wavedec(signal_Temp, wavelet_type, level=decomp_level)

# for I_In

    # Extract features from coefficients
    features_I_In = {}
    for i, coeff in enumerate(coeffs_I_In):
        if len(coeff) == 0:
            continue
        # features: energy, entropy, variance
        features_I_In[f'I_In_wavelet_energy_level_{i}'] = np.sum(coeff**2)
        features_I_In[f'I_In_wavelet_entropy_level_{i}'] = -np.sum(coeff**2 * np.log(coeff**2 + 1e-10))
        features_I_In[f'I_In_wavelet_var_level_{i}'] = np.var(coeff)

    # Add fileno to map features back
    features_I_In['fileno'] = fileno
    wavelet_features_I_In.append(features_I_In)


#for I_Out
    features_I_Out = {}
    for i, coeff in enumerate(coeffs_I_Out):
        if len(coeff) == 0:
            continue
        # features: energy, entropy,
        features_I_Out[f'I_Out_wavelet_energy_level_{i}'] = np.sum(coeff**2)
        features_I_Out[f'I_Out_wavelet_entropy_level_{i}'] = -np.sum(coeff**2 * np.log(coeff**2 + 1e-10))
        features_I_Out[f'I_Out_wavelet_var_level_{i}'] = np.var(coeff)

    wavelet_features_I_Out.append(features_I_Out)



#for V_In
    features_V_In = {}
    for i, coeff in enumerate(coeffs_V_In):
        if len(coeff) == 0:
            continue
        # features: energy, entropy,
        features_V_In[f'V_In_wavelet_energy_level_{i}'] = np.sum(coeff**2)
        features_V_In[f'V_In_wavelet_entropy_level_{i}'] = -np.sum(coeff**2 * np.log(coeff**2 + 1e-10))
        features_V_In[f'V_In_wavelet_var_level_{i}'] = np.var(coeff)

    wavelet_features_V_In.append(features_V_In)


#for V_Out
    features_V_Out = {}
    for i, coeff in enumerate(coeffs_V_Out):
        if len(coeff) == 0:
            continue
        # features: energy, entropy,
        features_V_Out[f'V_Out_wavelet_energy_level_{i}'] = np.sum(coeff**2)
        features_V_Out[f'V_Out_wavelet_entropy_level_{i}'] = -np.sum(coeff**2 * np.log(coeff**2 + 1e-10))
        features_V_Out[f'V_Out_wavelet_var_level_{i}'] = np.var(coeff)

    wavelet_features_V_Out.append(features_V_Out)

#for Temp
    features_Temp = {}
    for i, coeff in enumerate(coeffs_Temp):
        if len(coeff) == 0:
            continue
        # features: energy, entropy,
        features_Temp[f'Temp_wavelet_energy_level_{i}'] = np.sum(coeff**2)
        features_Temp[f'Temp_wavelet_entropy_level_{i}'] = -np.sum(coeff**2 * np.log(coeff**2 + 1e-10))
        features_Temp[f'Temp_wavelet_var_level_{i}'] = np.var(coeff)

    wavelet_features_Temp.append(features_Temp)

# Convert to DataFrame
wavelet_df_I_In = pd.DataFrame(wavelet_features_I_In)
wavelet_df_I_Out = pd.DataFrame(wavelet_features_I_Out)
wavelet_df_V_In = pd.DataFrame(wavelet_features_V_In)
wavelet_df_V_Out = pd.DataFrame(wavelet_features_V_Out)
wavelet_df_Temp = pd.DataFrame(wavelet_features_Temp)


wavelet_df_test = pd.concat([wavelet_df_I_In, wavelet_df_I_Out, wavelet_df_V_In, wavelet_df_V_Out, wavelet_df_Temp], axis=1)
wavelet_df_test = wavelet_df_test.set_index('fileno')

In [14]:
wavelet_df_test.isna().sum()

I_In_wavelet_energy_level_0      0
I_In_wavelet_entropy_level_0     0
I_In_wavelet_var_level_0         0
I_In_wavelet_energy_level_1      0
I_In_wavelet_entropy_level_1     0
I_In_wavelet_var_level_1         0
I_In_wavelet_energy_level_2      0
I_In_wavelet_entropy_level_2     0
I_In_wavelet_var_level_2         0
I_In_wavelet_energy_level_3      0
I_In_wavelet_entropy_level_3     0
I_In_wavelet_var_level_3         0
I_Out_wavelet_energy_level_0     0
I_Out_wavelet_entropy_level_0    0
I_Out_wavelet_var_level_0        0
I_Out_wavelet_energy_level_1     0
I_Out_wavelet_entropy_level_1    0
I_Out_wavelet_var_level_1        0
I_Out_wavelet_energy_level_2     0
I_Out_wavelet_entropy_level_2    0
I_Out_wavelet_var_level_2        0
I_Out_wavelet_energy_level_3     0
I_Out_wavelet_entropy_level_3    0
I_Out_wavelet_var_level_3        0
V_In_wavelet_energy_level_0      0
V_In_wavelet_entropy_level_0     0
V_In_wavelet_var_level_0         0
V_In_wavelet_energy_level_1      0
V_In_wavelet_entropy_level_1     0
V_In_wavelet_var_level_1         0
V_In_wavelet_energy_level_2      0
V_In_wavelet_entropy_level_2     0
V_In_wavelet_var_level_2         0
V_In_wavelet_energy_level_3      0
V_In_wavelet_entropy_level_3     0
V_In_wavelet_var_level_3         0
V_Out_wavelet_energy_level_0     0
V_Out_wavelet_entropy_level_0    0
V_Out_wavelet_var_level_0        0
V_Out_wavelet_energy_level_1     0
V_Out_wavelet_entropy_level_1    0
V_Out_wavelet_var_level_1        0
V_Out_wavelet_energy_level_2     0
V_Out_wavelet_entropy_level_2    0
V_Out_wavelet_var_level_2        0
V_Out_wavelet_energy_level_3     0
V_Out_wavelet_entropy_level_3    0
V_Out_wavelet_var_level_3        0
Temp_wavelet_energy_level_0      0
Temp_wavelet_entropy_level_0     0
Temp_wavelet_var_level_0         0
Temp_wavelet_energy_level_1      0
Temp_wavelet_entropy_level_1     0
Temp_wavelet_var_level_1         0
Temp_wavelet_energy_level_2      0
Temp_wavelet_entropy_level_2     0
Temp_wavelet_var_level_2         0
Temp_wavelet_energy_level_3      0
Temp_wavelet_entropy_level_3     0
Temp_wavelet_var_level_3         0
dtype: int64

In [15]:
wavelet_df_test

I_In_wavelet_energy_level_0  ...  Temp_wavelet_var_level_3
fileno                               ...                          
200                      106.187416  ...                  0.009710
201                       95.984631  ...                  0.012953
202                      101.636091  ...                  0.010743
203                      106.779900  ...                  0.007831
204                      103.209659  ...                  0.010499
...                             ...  ...                       ...
3995                      90.806206  ...                  0.016158
3996                      90.239072  ...                  0.016388
3997                      87.331630  ...                  0.017232
3998                      86.141918  ...                  0.019065
3999                      88.500349  ...                  0.020086

[3200 rows x 60 columns]

In [16]:
from sklearn.model_selection import train_test_split, KFold, cross_val_predict, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score
import xgboost as xgb

def xgb_(X, y, num_folds=5):

    kf = KFold(n_splits=num_folds, shuffle=True, random_state=24)

    f1_scores = []
    accuracies = []
    precisions = []

    for fold_idx, (train_idx, test_idx) in enumerate(kf.split(X)):
        print(f"Fold {fold_idx + 1}:")

        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

        # Initialize and train the XGBoost model with regularization
        xgb1 = xgb.XGBClassifier(
            objective="multi:softmax",
            random_state=42,
            alpha=0.1,
            reg_lambda=0.1,
            max_depth=4,
            min_child_weight=10,
            subsample=0.8,
            colsample_bytree=0.8
        )

        # Fit the model
        xgb1.fit(X_train.to_numpy(), y_train.to_numpy().ravel())

        # Make predictions
        y_pred = xgb1.predict(X_test.to_numpy())

        # Ensure y_test is 1D for comparison
        y_test = y_test.to_numpy().ravel().astype(int)
        y_pred = y_pred.astype(int)

        # Calculate and store F1-score for this fold
        f1 = f1_score(y_test, y_pred, average='weighted')
        f1_scores.append(f1)

        # Calculate and store accuracy and precision for this fold
        accuracy = accuracy_score(y_test, y_pred)
        accuracies.append(accuracy)
        precision = precision_score(y_test, y_pred, average='weighted')
        precisions.append(precision)

        print(classification_report(y_test, y_pred))
        print(f"Fold {fold_idx + 1} F1-score: {f1:.4f}")
        print(f"Fold {fold_idx + 1} Accuracy: {accuracy:.4f}")
        print(f"Fold {fold_idx + 1} Precision: {precision:.4f}")

        # Calculate and print confusion matrix
        cm = confusion_matrix(y_test, y_pred)
        print("Confusion Matrix:")
        print(cm)

        print("-" * 30)

    # Calculate and print average metrics across all folds
    avg_f1 = np.mean(f1_scores)
    avg_accuracy = np.mean(accuracies)
    avg_precision = np.mean(precisions)

    print(f"Average F1-score across {num_folds} folds: {avg_f1:.4f}")
    print(f"Average Accuracy across {num_folds} folds: {avg_accuracy:.4f}")
    print(f"Average Precision across {num_folds} folds: {avg_precision:.4f}")

    # Final model: Train on the entire dataset
    print("Training final model on the entire dataset...")
    X_train_final, X_test_final, y_train_final, y_test_final = train_test_split(X, y, test_size=0.2, random_state=42)

    # Final model with regularization
    final_model = xgb.XGBClassifier(
        objective="multi:softmax",
        random_state=42,
        alpha=1,
        reg_lambda=1,
        # max_depth=5,
        min_child_weight=20,
        # subsample=0.8,
        # colsample_bytree=0.8
    )

    # Train on the entire dataset
    final_model.fit(X_train_final.to_numpy(), y_train_final.to_numpy().ravel())

    # Evaluate the final model on the test set
    y_pred_final = final_model.predict(X_test_final.to_numpy())

    # Calculate accuracy, precision, confusion matrix for final model
    final_accuracy = accuracy_score(y_test_final, y_pred_final)
    final_precision = precision_score(y_test_final, y_pred_final, average='weighted')
    final_cm = confusion_matrix(y_test_final, y_pred_final)

    print(f"Final Model Accuracy: {final_accuracy:.4f}")
    print(f"Final Model Precision: {final_precision:.4f}")
    print("Final Model Confusion Matrix:")
    print(final_cm)

    # Save the final model
    # with open('XGB_final_model.pkl', 'wb') as f:
    #     pickle.dump(final_model, f)
    # files.download('XGB_final_model.pkl')



In [17]:
xgb_ (pd.concat([wavelet_df_train, wavelet_df_test]), pd.concat([train_target, test_target]))

Fold 1:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       210
           1       0.94      0.96      0.95       194
           2       0.95      0.95      0.95       199
           3       0.99      0.99      0.99       197

    accuracy                           0.97       800
   macro avg       0.97      0.97      0.97       800
weighted avg       0.97      0.97      0.97       800

Fold 1 F1-score: 0.9713
Fold 1 Accuracy: 0.9712
Fold 1 Precision: 0.9715
Confusion Matrix:
[[206   0   4   0]
 [  0 187   6   1]
 [  1   9 189   0]
 [  0   2   0 195]]
------------------------------
Fold 2:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       201
           1       0.93      0.92      0.93       191
           2       0.93      0.93      0.93       208
           3       0.97      0.98      0.98       200

    accuracy                           0.95       800
   macro avg       0.95 

In [18]:
train_target

color
0        0
1        0
2        0
3        0
4        0
..     ...
795      3
796      3
797      3
798      3
799      3

[800 rows x 1 columns]

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score

In [25]:
import sklearn

In [26]:
model2 = RandomForestClassifier()
model2.fit(wavelet_df_train, train_target)
y_pred = model2.predict(wavelet_df_test)
accura = sklearn.metrics.accuracy_score(test_target, y_pred)
print(accura)
precision_score = sklearn.metrics.precision_score(test_target, y_pred, average='weighted')
print(precision_score, " weighted")
print(classification_report(test_target, y_pred))

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


0.764375
0.7700556561585041  weighted
              precision    recall  f1-score   support

           0       0.98      0.90      0.93       800
           1       0.64      0.67      0.66       800
           2       0.73      0.82      0.77       800
           3       0.73      0.67      0.70       800

    accuracy                           0.76      3200
   macro avg       0.77      0.76      0.77      3200
weighted avg       0.77      0.76      0.77      3200



In [40]:
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score

final_model = xgb.XGBClassifier(
    # objective="multi:softmax",
    # random_state=42,
    alpha=10,
    reg_lambda=1,
    # max_depth=10,
    min_child_weight=10,
    # subsample=0.8,
    colsample_bytree=0.8
)

final_model.fit(wavelet_df_train, train_target)

y_pred_final = final_model.predict(wavelet_df_test)

final_accuracy = accuracy_score(test_target, y_pred_final)
final_precision = precision_score(test_target, y_pred_final, average='weighted')
final_cm = confusion_matrix(test_target, y_pred_final)

print(f"Final Model Accuracy: {final_accuracy:.4f}")
print(f"Final Model Precision: {final_precision:.4f}")
print("Final Model Confusion Matrix:")
print(final_cm)

Final Model Accuracy: 0.8000
Final Model Precision: 0.8128
Final Model Confusion Matrix:
[[718   0  80   2]
 [  0 585 130  85]
 [ 14  47 732   7]
 [  0 275   0 525]]
